# Generated by Django 6.0.7 on 2026-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('referral_status', models.TextField(choices=[('Not asking', 'Not asking'), ('Referral required', 'Referral required'), ('Referral asked', 'Referral asked'), ('Referral got', 'Referral got'), ('Other', 'Other')], default='Not asking')),
                ('status', models.TextField(choices=[('To Apply', 'To Apply'), ('Applied', 'Applied'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Not considering', 'Not considering'), ('Other', 'Other'), ('Pending', 'Pending')], default='To Apply')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('official_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('min_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['status'], name='job_status_idx'), models.Index(fields=['referral_status'], name='job_referral_status_idx'), models.Index(fields=['company_name'], name='job_company_name_idx'), models.Index(fields=['official_id'], name='job_official_id_idx'), models.Index(fields=['title'], name='job_title_idx')],
            },
        ),
    ]
