# Generated by Django 6.0.7 on 2026-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUniqueKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_unique_keys',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='secondary_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
