# Generated by Django 6.0.7 on 2026-08-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobuniquekey_job_secondary_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
