# Generated by Django 6.0.7 on 2026-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_analysis_job_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_custom_resume_generated',
            field=models.BooleanField(default=False),
        ),
    ]
