# Generated by Django 6.0.7 on 2026-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobuniquekey_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.TextField(choices=[('To Apply', 'To Apply'), ('Applied', 'Applied'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Not considering', 'Not considering'), ('Other', 'Other'), ('Pending', 'Pending'), ('Duplicate', 'Duplicate')], default='To Apply'),
        ),
    ]
