# Generated by Django 6.0.7 on 2026-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_manual_created',
            field=models.BooleanField(default=True),
        ),
    ]
