# Generated by Django 6.0.7 on 2026-08-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='career_portal_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='referral_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
