# Generated by Django 6.0.7 on 2026-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_career_portal_url_company_referral_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.TextField(blank=True, choices=[('topCompany', 'Top company'), ('blacklist', 'Blacklist'), ('normal', 'Normal')], null=True),
        ),
    ]
