# Generated by Django 6.0.7 on 2026-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_scraper',
            field=models.BooleanField(default=False),
        ),
    ]
