import os

CLAUDE_CLI_BINARY = os.path.expanduser('~/.local/bin/claude')
CLAUDE_CLI_TIMEOUT_SECONDS = 120

MAX_SUMMARY_CHARS = 220
MAX_BULLET_CHARS = 200
MAX_SKILL_ITEM_CHARS = 60
MAX_SKILLS_PER_CATEGORY = 8
